// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docSidebar: [
    'index',
    {
      type: 'category',
      label: '基础理论',
      items: [{ type: 'autogenerated', dirName: 'theory' }],
    },
    {
      type: 'category',
      label: '设备指南',
      items: [{ type: 'autogenerated', dirName: 'equipment' }],
    },
    'contributing',
    {
      type: 'category',
      label: 'NINA',
      items: [
        {
          type: 'category',
          label: '文档',
          items: [
            { type: 'doc', id: 'NINA/index', label: '介绍' },
            { type: 'doc', id: 'NINA/requirements', label: '系统要求' },
            {
              type: 'category',
              label: '选项卡',
              items: [
                { type: 'doc', id: 'NINA/tabs/equipment/equipment', label: '概述' },
                {
                  type: 'category',
                  label: '设备',
                  items: [
                    { type: 'doc', id: 'NINA/tabs/equipment/camera', label: '相机' },
                    { type: 'doc', id: 'NINA/tabs/equipment/filterwheel', label: '滤镜轮' },
                    { type: 'doc', id: 'NINA/tabs/equipment/focuser', label: '调焦器' },
                    { type: 'doc', id: 'NINA/tabs/equipment/rotator', label: '旋转器' },
                    { type: 'doc', id: 'NINA/tabs/equipment/telescope', label: '望远镜' },
                    { type: 'doc', id: 'NINA/tabs/equipment/guider', label: '导星' },
                    { type: 'doc', id: 'NINA/tabs/equipment/switch', label: '开关' },
                    { type: 'doc', id: 'NINA/tabs/equipment/flatpanel', label: '平场板' },
                    { type: 'doc', id: 'NINA/tabs/equipment/weather', label: '气象' },
                    { type: 'doc', id: 'NINA/tabs/equipment/dome', label: '圆顶' },
                    { type: 'doc', id: 'NINA/tabs/equipment/safetymonitor', label: '安全监控' },
                  ],
                },
                { type: 'doc', id: 'NINA/tabs/skyatlas', label: '天图集' },
                { type: 'doc', id: 'NINA/tabs/framing', label: '构图助手' },
                { type: 'doc', id: 'NINA/tabs/flatwizard', label: '平场向导' },
                { type: 'doc', id: 'NINA/tabs/sequencer', label: '序列器' },
                { type: 'doc', id: 'NINA/tabs/imaging', label: '拍摄' },
                {
                  type: 'category',
                  label: '选项',
                  items: [
                    { type: 'doc', id: 'NINA/tabs/options/general', label: '常规' },
                    { type: 'doc', id: 'NINA/tabs/options/equipment', label: '设备' },
                    { type: 'doc', id: 'NINA/tabs/options/autofocus', label: '自动对焦' },
                    { type: 'doc', id: 'NINA/tabs/options/dome', label: '圆顶' },
                    { type: 'doc', id: 'NINA/tabs/options/imaging', label: '拍摄' },
                    { type: 'doc', id: 'NINA/tabs/options/platesolving', label: '解析' },
                  ],
                },
                {
                  type: 'category',
                  label: '插件',
                  items: [
                    { type: 'doc', id: 'NINA/tabs/plugins/installed', label: '已安装' },
                    { type: 'doc', id: 'NINA/tabs/plugins/available', label: '可用' },
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: '序列器',
              items: [
                { type: 'doc', id: 'NINA/sequencer/overview', label: '概述' },
                {
                  type: 'category',
                  label: '传统序列器',
                  items: [
                    { type: 'doc', id: 'NINA/sequencer/simple/simple', label: '概述' },
                    { type: 'doc', id: 'NINA/sequencer/simple/sequencing', label: '序列设置' },
                  ],
                },
                {
                  type: 'category',
                  label: '高级序列器',
                  items: [
                    { type: 'doc', id: 'NINA/sequencer/advanced/advanced', label: '概述' },
                    { type: 'doc', id: 'NINA/sequencer/advanced/instructions', label: '指令' },
                    { type: 'doc', id: 'NINA/sequencer/advanced/conditions', label: '循环条件' },
                    { type: 'doc', id: 'NINA/sequencer/advanced/triggers', label: '触发器' },
                    { type: 'doc', id: 'NINA/sequencer/advanced/expressions', label: '表达式 (NINA 3.3)' },
                    { type: 'doc', id: 'NINA/sequencer/advanced/simpletoadvanced', label: '从传统到高级' },
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: '高级主题',
              items: [
                { type: 'doc', id: 'NINA/advanced/autofocus', label: '自动对焦' },
                { type: 'doc', id: 'NINA/advanced/meridianflip', label: '自动中天翻转' },
                { type: 'doc', id: 'NINA/advanced/camerasimulator', label: '相机模拟器' },
                { type: 'doc', id: 'NINA/advanced/bulbshutter', label: 'B门快门控制' },
                { type: 'doc', id: 'NINA/advanced/dithering', label: '抖动' },
                { type: 'doc', id: 'NINA/advanced/backlashmeasurement', label: '调焦器回差测量' },
                { type: 'doc', id: 'NINA/advanced/framingassistant', label: '构图助手' },
                {
                  type: 'category',
                  label: '文件格式',
                  items: [
                    { type: 'doc', id: 'NINA/advanced/file_formats/tiff', label: 'TIFF' },
                    { type: 'doc', id: 'NINA/advanced/file_formats/fits', label: 'FITS' },
                    { type: 'doc', id: 'NINA/advanced/file_formats/xisf', label: 'XISF' },
                  ],
                },
                { type: 'doc', id: 'NINA/advanced/guiding', label: '导星' },
                { type: 'doc', id: 'NINA/advanced/platesolving', label: '解析' },
              ],
            },
            {
              type: 'category',
              label: '故障排查',
              items: [
                { type: 'doc', id: 'NINA/troubleshooting/general', label: '常规' },
                { type: 'doc', id: 'NINA/troubleshooting/ascom_connection_issues', label: 'ASCOM 连接问题' },
                { type: 'doc', id: 'NINA/troubleshooting/ioptron', label: 'iOptron 赤道仪设置' },
                { type: 'doc', id: 'NINA/troubleshooting/eqmod', label: 'EQMOD 设置' },
                { type: 'doc', id: 'NINA/troubleshooting/altair_dualgain', label: 'Altair 双增益' },
                { type: 'doc', id: 'NINA/troubleshooting/planetarium', label: '星图软件设置' },
                { type: 'doc', id: 'NINA/troubleshooting/qhy_driver_update', label: 'QHY 驱动' },
                { type: 'doc', id: 'NINA/troubleshooting/render_issues', label: '显示问题' },
                { type: 'doc', id: 'NINA/troubleshooting/folder_browser_only_desktop', label: '文件夹浏览器仅显示桌面' },
              ],
            },
            { type: 'doc', id: 'NINA/glossary', label: '术语表' },
            { type: 'doc', id: 'NINA/license', label: '许可协议' },
            { type: 'doc', id: 'NINA/3rd-party-license', label: '第三方许可' },
          ],
        },
        {
          type: 'category',
          label: '快速入门',
          items: [
            { type: 'doc', id: 'NINA/quickstart/uioverview', label: '界面概览' },
            { type: 'doc', id: 'NINA/quickstart/equipment', label: '连接设备' },
            { type: 'doc', id: 'NINA/quickstart/settings', label: '完成设置' },
            { type: 'doc', id: 'NINA/quickstart/focusing', label: '对焦' },
            { type: 'doc', id: 'NINA/quickstart/sequence', label: '开始序列' },
          ],
        },
        {
          type: 'category',
          label: '贡献',
          items: [
            // { type: 'doc', id: 'NINA/contributing/contributing', label: '完善文档' },
            { type: 'doc', id: 'NINA/contributing/howtosetupdev', label: '如何搭建开发环境' },
            { type: 'doc', id: 'NINA/contributing/localization', label: '本地化' },
            { type: 'doc', id: 'NINA/contributing/plugins', label: '插件' },
            { type: 'doc', id: 'NINA/contributing/ecosystem', label: '生态' },
          ],
        },
      ],
    },
  ],

  regulationsSidebar: [
    { type: 'doc', id: 'regulations/index', label: '总览' },
    // 'regulations/charter',
    'regulations/equipment-management-measures',
    'regulations/permission-assessment',
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;